Connect/Connect/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller    
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult Index()
        {
            return View();
        }
   

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Connect/Connect/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ServiceController : Controller
    {

        public IActionResult Connect()
        {
            return View();
        }

        public IActionResult API()
        {
            return View();
        }
        public IActionResult PaymentJs()
        {
            return View();
        }

        public IActionResult Store_Creation()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Connect/Connect/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "EntornoFiservUDI";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<style>
    .hide {
        display: none !important;
    }

    .section1 {
        width: 50%;
        float: left;
        height: 100vh;
        box-sizing: border-box;
        border-right: 1vw;
        margin: 0;
        padding: 0;
    }

    .section2 {
        width: 50%;
        float: left;
        height: 100vh;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
</style>
<meta charset=UTF-8>
<center>
    <div class="col-4">
        <h1>Entorno de pruebas de UDI</h1>
    </div>
    <hr style="height:1px; color:#aaa;" />
    <div>
        <h4>Connect</h4>
        <a asp-area="" asp-controller="Service" asp-action="Connect">
            <img src="/Images/API_illustration_light.png" width="500" height="300">
        </a>

    </div>
    <hr style="height:1px; color:#aaa;" />
    <div>
        <h4>API</h4>
        <a asp-area="" asp-controller="Service" asp-action="API">
            <img src="/Images/apisimple.jpg" width="500" height="240">
        </a>
    </div>
    <hr style="height:1px; color:#aaa;" />
    <div>
        <h4>Documentación</h4>
        <a href="https://docs.firstdata.com/org/FDMexico" target="_blank">
            <img src="/Images/post_ap-76_cedocs.jpg" width="400" height="240">
        </a>
    </div>
    <hr style="height:1px; color:#aaa;" />
</center>